version: 2
updates:
  # Maintain Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 10
    target-branch: "master"
    groups:
      dependencies:
        patterns:
          - "*"

  # Maintain GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 10
    target-branch: "master"
